export const env = {
  EXPRESS_API_TODOS_URL: process.env.NEXT_PUBLIC_EXPRESS_API_TODOS_URL,
  EXPRESS_API_USERS_URL: process.env.NEXT_PUBLIC_EXPRESS_API_USERS_URL,
  EXPRESS_API_SUBTODOS_URL: process.env.NEXT_PUBLIC_EXPRESS_API_SUBTODOS_URL,
}